# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo:4.4.6
    container_name: manga-store
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - /Desktop/manga-store-backend/data:/data/db

  # mongo-express:
  #   image: mongo-express
  #   container_name: manga-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: example
  #     ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/