version: '3.7'

services:
  mongo:
    image: mongo:4.4.6
    container_name: manga-store
    restart: always
    environment:
      MONGO_INITDB_DATABASE: manga-store-db
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      DB_USERNAME: root
      DB_PASSWORD: example
      DB_PORT: 27017
    ports:
      - 27017:27017
    volumes:
      - ~/Desktop/manga-store-backend/data:/data/db
